records/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('',\
        ################################ Main dash forms
        (r'^$', 'records.views.home'),
        (r'^volunteer/$', 'records.views.volunteer'),
        (r'^volunteer/change/(?P<id>\d+)/$', 'records.views.changeVol'),
        (r'^profile/$', 'records.views.profile'),
        (r'^family/$', 'records.views.family'),
        (r'^pickup/$', 'records.views.pickup'),
        (r'^students/add/$', 'records.views.addStudent'),
        (r'^students/$', 'records.views.addStudent'),
        (r'^students/change/(?P<id>\d+)/$', 'records.views.changeStudent'),
        (r'^guardians/$', 'records.views.guardians'),
        (r'^contacts/$', 'records.views.ecf'),

        ################################# Application Process
        (r'^apply/guardians/$', 'records.views.guardians'),
        (r'^apply/profile/$', 'records.views.profile'),
        (r'^apply/family/$', 'records.views.family'),
        (r'^apply/volunteer/$', 'records.views.volunteer'),
        (r'^apply/$', 'records.views.apply'),
        (r'^apply/questions/parent/(?P<id>\d+)/$', 'records.views.parent'),
        (r'^apply/questions/(?P<id>\d+)/$', 'records.views.questions'),
        (r'^apply/questions/mssq/(?P<id>\d+)/$', 'records.views.mssq'),
        (r'^apply/current/(?P<id>\d+)/$', 'records.views.current'),
        (r'^apply/complete/$', 'records.views.appcontinue'),
        (r'^apply/complete/(?P<id>\d+)/$', 'records.views.appcomplete'),

        ################################# Registraton and re-enrollment process
        (r'^register/$', 'records.views.register'),
        (r'^register/(?P<id>\d+)/$', 'records.views.registerStudent'),
        (r'^enroll/$', 'records.views.enroll'),
        (r'^enroll/(?P<id>\d+)/$', 'records.views.enrollStudent'),
)

urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
admin.autodiscover()

from django.views.generic.simple import redirect_to

from registration.forms import RegistrationFormUniqueEmail
from endpoint import Endpoint

from settings import DEBUG, PROJECT_DIR
import os

if DEBUG:
    urlpatterns = patterns('',\
            (r'^media/(?P<path>.*)$', 'django.views.static.serve',\
            {'document_root': os.path.join(PROJECT_DIR, 'media/')}),

            (r'^admin_media/(?P<path>.*)$', 'django.views.static.serve',\
            {'document_root': os.path.join(PROJECT_DIR, 'admin_media/')}),
    )
else:
    urlpatterns = patterns('',)

urlpatterns += patterns('',
    # This is the return url for processing the IPN for paypal
    (r'^endpoint/$', Endpoint(),),

    ################################# Registration
    (r'^accounts/profile/$', redirect_to, {'url':'/'}),
    (r'^accounts/register/$', 'registration.views.register',\
            {'form_class': RegistrationFormUniqueEmail},),
    (r'^accounts/', include('registration.urls')),

    ################################# Admin
    # Mail
    (r'^admin/(?P<app_label>[\d\w]+)/(?P<model_name>[\d\w]+)/mail/$',\
            'utils.mail',),
    # For export to csv
    (r'^admin/(?P<app_label>[\d\w]+)/(?P<model_name>[\d\w]+)/csv/$',\
            'utils.admin_list_export'),
    # For Printing
    (r'^admin/(?P<app_label>[\d\w]+)/(?P<model_name>[\d\w]+)/(?P<pk>[\d]+)/print/$',\
            'records.views.print_detail'),
    (r'^admin/(.*)', admin.site.root),

    ################ Parent Dashboard, Application and Enrollment
    (r'^records/', include('records.urls')),

    ################################### Menu urls
    (r'^menu/', include('menu.urls')),

    ############### Blog urls
    (r'blog/', include('blog.urls')),
    (r'^comments/', include('django.contrib.comments.urls')),

    ################## Media_logs
    (r'videos/', include('media_logs.urls.videos')),
    (r'photos/', include('media_logs.urls.photos')),

    ########### our_people
    (r'our_people/', include('our_people.urls')),

    ######### Basic site views
    (r'^$', 'homeviews.home'),
    (r'^calendar/$', 'homeviews.calendar'),
)

records/models.py
import datetime
from django.db import models
from datetime import datetime, timedelta
from django.contrib.localflavor.us.models import PhoneNumberField, USStateField

gender_choices = (
    ('m', 'Male'),
    ('f', 'Female')
)

relationship_choices = (
    ('mother', 'Mother'),
    ('father', 'Father'),
    ('grandfather', 'Grandfather'),
    ('grandmother', 'Grandmother'),
    ('aunt', 'Aunt'),
    ('uncle', 'Uncle'),
    ('brother', 'Brother'),
    ('sister', 'Sister'),
    ('cousin', 'Cousin'),
    ('other', 'Other'),
)

scale_choices = (
    ('5', '5'),
    ('4', '4'),
    ('3', '3'),
    ('2', '2'),
    ('1', '1'),
)

from constants import title_choices, grade_choices, gender_choices

attend_choices = (
    ('y', 'Daily'),
    ('s', 'Some'),
    ('n', 'Never'),
)

from django.contrib.auth.models import User
#from people.models import EmergencyContacts
class UserProfile(models.Model):
    user = models.ForeignKey(User, unique=True, )
    addressee = models.CharField(max_length=70, verbose_name="Account Name",help_text="This could be 'The Smiths' or 'John & Diane Smith'",)
    street_address = models.CharField(max_length=100)
    city = models.CharField(max_length=50)
    state = USStateField(default='GA')
    zip = models.CharField(max_length=5)
    primary_phone = PhoneNumberField()

    def students(self):
        ss = Student.objects.filter(user=self.user)
        string=''
        for s in ss:
            string += s.name() + ', '
        return string


    def guardians(self):
        from people.models import Guardian
        gs = Guardian.objects.filter(user=self.user)
        string=''
        for g in gs:
            string += "%s %s, " % (g.first, g.last)
        return string

    def email(self):
        return self.user.email

    def __unicode__(self):
        return self.addressee

    def emergency_contacts(self):
        from people.models import EmergencyContacts
        ec = EmergencyContacts.objects.get(user=self)
        return "%s @%s, %s @%s, Doctor %s @%s" % (ec.contact1, ec.phone1,\
                ec.contact2, ec.phone2, ec.doctor, ec.doctor_phone)

    def ongoing_app_form(self):
        if Student.objects.filter(user=self, application_form_complete=False):
            return True
        else:
            return False

    def pending_application(self):
        if Student.objects.filter(user=self, application_form_complete=True,
                decision_made=None):
            return True
        else:
            return False

class Student(models.Model):
    user = models.ForeignKey('UserProfile')
    last = models.CharField(max_length=50)
    first = models.CharField(max_length=30)
    middle = models.CharField(max_length=30, blank=True)
    preferred_name = models.CharField(max_length=30)
    present_grade = models.CharField(max_length=3, choices=grade_choices)
    next_grade = models.CharField(max_length=3, choices=grade_choices)
    date_of_birth = models.DateField()
    gender = models.CharField(max_length=1, choices=gender_choices)
    living_with_choices = (
        ('b', 'Both Parents'),
        ('m', 'Mother'),
        ('f', 'Father'),
        ('o', 'Other'),
    )
    living_with = models.CharField(max_length=1, choices=living_with_choices)
    changes_affect = models.TextField(blank=True)
    allergies = models.BooleanField()
    allergy_description = models.TextField(blank=True)

    # Application Process
    application_form_completed_on = models.DateField(blank=True, null=True)
    application_form_complete = models.BooleanField()

    application_payment_completed_on = models.DateField(blank=True,null=True)
    application_payment_complete = models.BooleanField()

    entrance_testing_scheduled_for = models.DateField(blank=True,null=True)
    entrance_testing_complete = models.BooleanField()

    parent_interview_scheduled_for = models.DateField(blank=True,null=True)
    parent_interview_complete = models.BooleanField()

    student_interview_scheduled_for = models.DateField(blank=True,null=True)
    student_interview_complete = models.BooleanField()

    decision_made = models.DateField(blank=True,null=True)
    student_accepted = models.BooleanField()

    # Registration Process
    registration_signed_paid = models.BooleanField()
    registration_signed_paid_on = models.DateField(blank=True,null=True)

    complete_documents = models.BooleanField()
    complete_documents_on = models.DateField(blank=True,null=True)

    custody_decision_received = models.BooleanField()
    custody_decision_received_on = models.DateField(blank=True,null=True)

    birth_certificate_received = models.BooleanField()
    birth_certificate_received_on = models.DateField(blank=True,null=True)

    immunization_record_received = models.BooleanField()
    immunization_record_received_on = models.DateField(blank=True,null=True )

    emergency_medical_card_received = models.BooleanField()
    emergency_medical_card_received_on = models.DateField(blank=True, null=True)

    plan = (
        ('1','This plan'),
        ('2', 'That plan'),
    )
    payment_plan =  models.CharField(max_length=1, choices=plan, blank=True)
    registration_complete = models.BooleanField()

    # General status
    currently_student = models.BooleanField()
    enrolled_for_upcoming_year = models.BooleanField()
    alumni = models.BooleanField()

    def age_in_years(self):
        return str((datetime.date.today()-self.date_of_birth).days/365)

    def guardians(self):
        from people.models import Guardian
        g=Guardian.objects.filter(user=self.user)
        s=''
        for o in g:
            s += o.__unicode__() + ', '
        return s

    def __unicode__(self):
        name = self.preferred_name + ' ' + self.last
        return name

    def name(self):
        return self.preferred_name + ' ' + self.last

    class Meta:
        verbose_name_plural = "students"

class BeforeAfterPrograms(models.Model):
    student = models.OneToOneField('Student')
    before_school = models.CharField(max_length=1, choices=attend_choices)
    after_school = models.CharField(max_length=1, choices=attend_choices)

from years.models import SchoolYear
class Enrollment(models.Model):
    student = models.ForeignKey('Student')
    year = models.ForeignKey(SchoolYear)
    date_paid = models.DateField()

    def __unicode__(self):
        return "%s - %s" % (self.student, self.year)

class Application(models.Model):
    student = models.OneToOneField('Student')
    scholastic_difficulties = models.BooleanField()
    learning_differences = models.BooleanField()
    special_education = models.BooleanField()
    extended_absences = models.BooleanField()
    physical_emotional = models.BooleanField()
    reason_to_not_attend = models.BooleanField()
    if_yes_explain = models.TextField(blank=True)
    interests_skills_hobbies = models.TextField(blank=True)
    why_enroll = models.TextField(blank=True)
    why_change_school = models.TextField(blank=True)
    hope_to_benefit = models.TextField(blank=True)
    entering_6th_7th_or_8th = models.BooleanField()

    signed = models.CharField(max_length=70)
    dated = models.DateField()

    def __unicode__(self):
        return self.student.preferred_name + ' ' + self.student.last + ' '  + str(self.dated)

class ParentPart(models.Model):
    application = models.OneToOneField('Application')
    why_believe = models.TextField(blank=True, )
    bible = models.TextField(blank=True)
    ways_follow_bible = models.TextField(blank=True)
    bible_as_parent = models.TextField(blank=True)
    ccs_help_as_christian_parent = models.TextField(blank=True)
    why_not_enrolling_siblings = models.TextField(blank=True)
    where_did_you_hear_about = models.TextField(blank=True)

    signed = models.CharField(max_length=70)
    dated = models.DateField()

    def __unicode__(self):
        return "%s %s" % (self.application, self.signed)

    class Meta:
        verbose_name_plural = "Parent Portion of Application"

class MiddleSchoolStudentQuestionnaire(models.Model):
    application = models.OneToOneField('Application')
    church_choices = (
        ('1', 'Almost every Sunday'),
        ('2', '2 or 3 times a month'),
        ('3', 'Once a month'),
        ('4', '3 or 4 times a year'),
    )
    church_attendance = models.CharField(max_length=1, choices=church_choices,\
            verbose_name="You attend church")
    grade_choices = (
        ('A', "I get mostly A's"),
        ('B', "I get mostly B's"),
        ('C', "I get mostly C's"),
        ('D', "I get mostly D's"),
    )
    grades = models.CharField(max_length=1, choices=grade_choices, verbose_name="Grades you get")
    activities_enjoy = models.TextField(verbose_name="Tell us about activities you enjoy")
    best_courses = models.TextField(verbose_name="Tell us about your favorite classes")
    worst_courses = models.TextField(verbose_name="Least favorite classes?")
    life = models.TextField(verbose_name="What do you envision doing with your life?")
    means_to_be_christian = models.TextField(verbose_name="What does being a Christian mean to you?" )
    other_choices = (
        ('1', 'I really enjoy doing things with others'),
        ('2', 'I enjoy doing things with others but also enjoy spending time with myself'),
        ('3', 'I would rather spend time alone than with others'),
    )
    with_others = models.CharField(max_length=1, choices=other_choices, verbose_name="Which best describes you?")
    music = models.CharField(max_length=1, choices=scale_choices)
    reading = models.CharField(max_length=1, choices=scale_choices)
    bible_study = models.CharField(max_length=1, choices=scale_choices)
    school = models.CharField(max_length=1, choices=scale_choices, verbose_name="Doing Homework")
    television = models.CharField(max_length=1, choices=scale_choices)
    attending_college = models.CharField(max_length=1, choices=scale_choices)
    athletics = models.CharField(max_length=1, choices=scale_choices)

records/forms.py
from records.models import UserProfile, Student, Application, MiddleSchoolStudentQuestionnaire, CurrentSchool, ParentPart

from people.models import Guardian, FamilyMember, AuthorizedPickUpPerson, Volunteer, EmergencyContacts

from django.forms import ModelForm
from django.forms import DateField
from django.forms.extras.widgets import SelectDateWidget


class VolunteerForm(ModelForm):
    class Meta:
        model = Volunteer
        exclude = ('user','date', 'classroom',
                'campus', 
                'academic', 
                'music', 
                'library', 
                'art', 
                'yearbook', 
                'office', 
                'fundraising',
                'maintenance', 
                'resources',
)

class ProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        exclude = ('user', 'has_completed_profile', 'has_added_guardians', 'has_added_church',
                   'has_added_family', 'has_signed_form', 'has_signed_contract', )

# These are the forms that are part of the application process


class StudentApplyForm(ModelForm):
    date_of_birth = DateField(widget=SelectDateWidget(years=[1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009]))
    class Meta:
        model = Student
#        exclude = ('application_completed', 'registration_signed_paid', 'currently_student', 'enrolled_for_upcoming_year', 'alumni', 'user', 'allergies', 'allergy_description','date', 'changes_affect')
        fields = ('last','first','middle','preferred_name','present_grade','next_grade','date_of_birth','gender','living_with')

class StudentAddForm(StudentApplyForm):
    class Meta:
        model = Student
        fields = ('last','first','middle','preferred_name','present_grade','next_grade','date_of_birth','gender','living_with', 'allergies', 'allergy_description',)
        

import datetime    
class ApplicationForm(ModelForm):
    dated = DateField(initial=datetime.date.today())
    class Meta:
        model = Application
        exclude = ('student')

class MSSQForm(ModelForm):
    dated = DateField(initial=datetime.date.today())
    class Meta:
        model = MiddleSchoolStudentQuestionnaire
        exclude = ('application')

class CurrentSchoolForm(ModelForm):
    class Meta:
        model = CurrentSchool
        exclude = ('application')

class ParentForm(ModelForm):
    dated = DateField(initial=datetime.date.today())
    class Meta:
        model = ParentPart
        exclude = ('application')

class EmergencyContactsForm(ModelForm):
    class Meta:
        model = EmergencyContacts
        exclude = ('user')

templates/records/addStudent.html
{% extends "records/base.html" %}

{% block content %}
<h2><em>Students</em></h2>
<p>Please use the following form to update student information.</p>

<form id="frmStudents" class="myForm_40em" name="input" action="." method="post">
 <div class="formPadding">


	{{form.as_p}}


<div class="submit"><input type="submit" value="Update &raquo;"></div>
</div></form>

{% endblock %}

templates/records/base.html
<html>
<head>
{% block head %}
<title>
{% block title %}Welcome to Django School{% endblock %}
</title>

<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<meta name="author" content="ligaturedesigns, sos.endofinternet.net">
<meta name="copyright" content="&copy; Skylar Saveland and Gary Brown">
<meta name="keywords" content="Web, application, Django, Python, school, information,system, learning, environment, open-source,">

<link rel="shortcut icon" href="favicon.ico">
<script src="{{MEDIA_URL}}/js/jquery-1.2.6.js" type="text/javascript"></script>
<script src="{{MEDIA_URL}}/js/jquery-menu.js" type="text/javascript"></script>

<link href="{{MEDIA_URL}}/css/reset.css"  rel="stylesheet" type="text/css" />
<link href="{{MEDIA_URL}}/css/style.css"  rel="stylesheet" type="text/css" />
{% endblock %}
{% block extrahead %}{% endblock %}
</head>
{% block onload %} <body> {% endblock %}
<div id="topright">
	<div class="logout-outer"><div class="logout-inner"><a href="/accounts/logout/">Logout &raquo;</a></div></div>
</div>

<div id="container">
<div id="left">
<dl id="topnav">
	<dt><a href="/">Home &raquo;</a></dt>
	<!--	
	<dt><b>Learn More &raquo;</b></dt>
	<dd>
		<ul>
			<li><a href="/learn/videos/">Videos &raquo;</a></li>
			<li><a href="/learn/weblog/">Weblog &raquo;</a></li>
		</ul>
	</dd>
	-->
	{% if not dash %}
	<dt><a href="/records/">Family Dashboard &raquo;</a></dt>
	{% else %}
	<dt><b>Enrolled Students &raquo;</b></dt>
	<dd>
		<ul>
			{% if students %}
			{% for s in students %}
			<li><a href="/records/students/change/{{s.id}}/">{{s}}</a></li>
			{% endfor %}
			{% endif %}
			<li><em><a href="/records/students/add/">Add a student &raquo;</a></em></li>
		</ul>
	</dd>
	<dt><a href="/records/guardians/">Parents/Guardians &raquo;</a></dt>
	<dt><a href="/records/contacts/">Emergency Contacts &raquo;</a></dt>
	<dt><a href="/records/pickup/">Student Pickup &raquo;</a></dt>
	<dt><a href="/records/family/">Grandparents/Friends &raquo;</a></dt>
	<dt><b>Volunteers &raquo;</b></dt>
	<dd>
		<ul>
			{% if volunteers %}
			{% for v in volunteers %}
			<li><a href="/records/volunteer/change/{{v.id}}/">{{v}}</a></li>
			{% endfor %}
			{% endif %}
			<li><em><a href="/records/volunteer/">Add a volunteer &raquo;</a></em></li>
		</ul>
	</dd>
	{% endif %}
</dl>
</div>

<div id="main">
	<div class="welcome">
{% if user.is_authenticated %}
You are currently logged in as: <em>{{user}}</em>
{% else %}
<em>You are not currently logged in</em>
{% endif %}

</div>
	<div id="content">
	{% block content %}{% endblock %}

	</div>
</div>
<div class="clear"></div>
</div>

</body>
</html>

templates/records/changeStudent.html
{% extends "records/base.html" %}

{% block content %}
<h2><em>Students</em></h2>
<p>Please use the following form to update student information.</p>

<form id="frmStudents" class="myForm_40em" name="input" action="." method="post">
 <div class="formPadding">


	{{form.as_p}}


<div class="submit"><input type="submit" value="Update &raquo;"></div>
</div></form>

{% endblock %}

templates/records/changeVol.html
{% extends "records/base.html" %}

{% block content %}
<h2><em>Volunteer Form</em></h2>
<p>Volunteer help is essential to controlling costs and providing many of the fine programs at our school. Parents have a
special interest in seeing that their children are well served. Grandparents and other relatives are also encouraged to
participate. Below is a list of areas where volunteer help is needed for effective school operation. Where can you help?</p>
<form class="myForm_100" id="frmVolunteer" name="input" action="." method="post"><div class="formPadding">
{% for field in form %}
{% ifequal field.name 'grade_papers' %}<div class="frmDivider"></div><p style="text-align:left; width:100%;"><h4 style="padding:0 0 0 0.5em;">Classroom</h4></p>{% endifequal %}
{% ifequal field.name 'supervise_playground' %}<p style="text-align:left; width:100%;"><h4 style="padding:0 0 0 0.5em;">Campus</h4></p>{% endifequal %}
{% ifequal field.name 'substitute' %}<p style="text-align:left; width:100%;"><h4 style="padding:0 0 0 0.5em;">Academic</h4></p>{% endifequal %}
{% ifequal field.name 'piano' %}<p style="text-align:left; width:100%;"><h4 style="padding:0 0 0 0.5em;">Music</h4></p>{% endifequal %}
{% ifequal field.name 'check_out' %}<p style="text-align:left; width:100%;"><h4 style="padding:0 0 0 0.5em;">Library and Media left</h4></p>{% endifequal %}
{% ifequal field.name 'bulletin_boards' %}<p style="text-align:left; width:100%;"><h4 style="padding:0 0 0 0.5em;">Arts</h4></p>{% endifequal %}
{% ifequal field.name 'photography' %}<p style="text-align:left; width:100%;"><h4 style="padding:0 0 0 0.5em;">Yearbook</h4></p>{% endifequal %}
{% ifequal field.name 'substitute_secretary' %}<p style="text-align:left; width:100%;"><h4 style="padding:0 0 0 0.5em;">Office</h4></p>{% endifequal %}
{% ifequal field.name 'jogathon' %}<p style="text-align:left; width:100%;"><h4 style="padding:0 0 0 0.5em;">Fundraising</h4></p>{% endifequal %}
{% ifequal field.name 'landscape' %}<p style="text-align:left; width:100%;"><h4 style="padding:0 0 0 0.5em;">Maintenance</h4></p>{% endifequal %}
{% ifequal field.name 'business_equipment' %}<p style="text-align:left; width:100%;"><h4 style="padding:0 0 0 0.5em;">Resources</h4></p>{% endifequal %}
      

	{% ifequal field.field.widget.input_type "text" %}
<div class="char_field">
	{% else %}
<div class="bool_field">
	{% endifequal %}

	{{ field.label_tag }} 
	{% if field.help_text %}{{ field.help_text }}{% endif %}
	{{ field }}
	{% if field.errors %}<div class="myerrors">{{ field.errors }}</div>{% endif %}
	</div>

{% endfor %}
<div class="submit"><input type="submit" value="Volunteer &raquo;"></div>
</div></form> 

{% endblock %}

templates/records/current.html
{% extends "records/base.html" %}

{% block content %}

<h2>Current School Information</h2>
<p>This is the introduction section or explanatory paragraph.</p>

<form class="myForm_40em" name="input" action="." method="post">

<div class="form">
<h4>Please tell us about your current school.</h4>
{% for field in form %}

<div class="field-wrapper">
			   {{field.label_tag }}
	{% if field.help_text %}<div class="help_text">{{field.help_text}}</div>{% endif %}
			   {{ field }}
	{% if field.errors %}{{ field.errors }}{% endif %}

</div>

{% endfor %}
<div class="submit"><input type="submit" value="Update &raquo;"></div>
</div>


</form> 

{% endblock %}

templates/records/emergency.html
{% extends "records/base.html" %}

{% block content %}
<h2>Emergency Contact Information</h2>
<p>In the event you cannot be reached, please list the names and phone numbers of 2 adults who will care for your child.</p>
<p>We also ask that you provide your doctor's name and phone number.</p>

<form class="myForm_40em" name="input" action="." method="post"><div class="formPadding">

{% for field in form %}

    <div class="field-wrapper">
		{% if field.field.required %}
			<b>{{ field.label_tag }}</b>
		{% else %}
			   {{field.label_tag }}
		{% endif %}
	<span class="field">{{ field }}</span>
    
	{% if field.help_text %}<div class="help_text">{{field.help_text}}</div>{% endif %}
	{% if field.errors %}{{ field.errors }}{% endif %}
    </div>

{% endfor %}

<div class="submit"><input type="submit" value="Update &raquo;"></div>

</div></form> 

{% endblock %}

templates/records/enroll.html
{% extends "base.html" %}


{% block content %}
{% if students %}
    <p>Please review your information below and make sure that it is up to date.
If you need to update something you can go to <a href="/records/">Parent Dashboard &raquo;</a></p>
    {% for s in students %}
	{% if s.enrolled_for_upcoming_year %}
		<p>{{s.preferred_name}} is enrolled for next year!</p>
        {% else %}
	        <p><a href="{{s.id}}/">Enroll {{s.preferred_name}} &raquo;</a></p>
	{% endif %}
    {% endfor %}
{%else%}
    <p>You have no students eligible <a href="/records/apply/">Apply now &raquo;</a> 
	or <a href="/records/apply/complete/">Check on the status of a pending application &raquo;</a>
    </p>
{% endif %}
{% endblock %}

templates/records/family.html
{% extends "records/base.html" %}

{% block content %}
<h2>CCS Connections</h2>
<p>This section provides a place for you to add family and/or friends who may be interested in receiving emails or mailings regarding CCS events. 
Grandparents are, of course, excellent resources to list in these fields. It is our hope that your entire extended family become involved in the 
education and nurture of your child.</p>

<form id="frmFamily" class="myForm_100" name="input" action="." method="post"><div class="formPadding">
	 
    {{ formset.management_form }}

    {% for form in formset.forms %}
<div class='inner-form'>
	{{form.as_p}}
</div>
		 
    {% endfor %}

<div class="submit"><input type="submit" value="Update &raquo;"></div>
</div></form>

{% endblock %}

templates/records/guardians.html
{% extends "records/base.html" %}

{% block content %}
<h2><em>Parents/Guardians</em></h2>
<p>The parent(s) or legal guardians for this household.</p>

<form class="myForm_100" name="input" action="." method="post"><div class="formPadding">
    {{ formset.management_form }}

    {% for form in formset.forms %}
<div class="inner-form">
        {% for field in form %}
  <div class="field-wrapper">
            {% ifnotequal field.name 'id' %}
                {% ifnotequal field.name 'user' %}
		{% if field.field.required %}
			<b>{{ field.label_tag }} </b>
		{% else %}
			{{field.label_tag}}
		{% endif %}
			{{field.help_text}}
	    {% endifnotequal %}{% endifnotequal %}

	<span class="field">{{ field }}</span>
            {% if field.errors %}
	<span class="errors">{{ field.errors }}</span>
			{% endif %}
  </div>
        {% endfor %}
</div>
    {% endfor %}
<div class="submit"><input type="submit" value="Update &raquo;"></div>
</div></form>

{% endblock %}

templates/records/mystudents.html
{% extends "records/base.html" %}

{% block content %}
{% if students %}
  {% for student in students %}
    <p>We have {{student.name}} in {{student.get_present_grade_display}} grade.</p>

    {% if student.application_completed %} Application Completed!
    {% else %}
	<p>This student has not been flagged as having completed the application process</p>
	<a>Here is where you go to do that</a> or call.
    {% endif %}

    {% if student.registration_signed_paid %} Registered!
    {% else %}
	<p>You need to register, this is where you do that:</p>
	<a href="/mystudents/register/{{student.id}}">link_to_register_form (Goes to templates/register_student.html </a>
    {% endif %}

    {% if student.currently_student %}
    	{{student.preferred_name}} has {% for teacher in student.teacher %}
						{{teacher.title}} {{teacher.name}}
					{% endfor %}
    {% endif %} 
    {% if not enrolled_for_upcoming_year and not alumni %} 
		You still need to enroll for the upcoming year <a>here</a>
    {% endif %}
  {% endfor %}
<p>Click here to add more students</p>
<a></a>

{% else %}
<p>You have not added any students yet</p>
<a>Click here to get started, the application, registration, and enrollment process takes less than 1 hour!</a>
{% endif %}



{% endblock %}